const countries = [
  { name: "Afganistan", value: "AF" },
  { name: "Almanya", value: "DE" },
  { name: "Amerika Birleşik Devletleri", value: "US" },
  { name: "Arnavutluk", value: "AL" },
  { name: "Avustralya", value: "AU" },
  { name: "Azerbaycan", value: "AZ" },
  { name: "Bahamalar", value: "BS" },
  { name: "Bahreyn", value: "BH" },
  { name: "Bangladeş", value: "BD" },
  { name: "Barbados", value: "BB" },
  { name: "Batı Sahra", value: "EH" },
  { name: "Belçika", value: "BE" },
  { name: "Belize", value: "BZ" },
  { name: "Benin", value: "BJ" },
  { name: "Beyaz Rusya", value: "BY" },
  { name: "Bhutan", value: "BT" },
  { name: "Birleşik Arap Emirlikleri", value: "AE" },
  { name: "Birleşik Krallık", value: "GB" },
  { name: "Bolivya", value: "BO" },
  { name: "Bosna-Hersek", value: "BA" },
  { name: "Botswana", value: "BW" },
  { name: "Brezilya", value: "BR" },
  { name: "Brunei", value: "BN" },
  { name: "Bulgaristan", value: "BG" },
  { name: "Burkina Faso", value: "BF" },
  { name: "Burundi", value: "BI" },
  { name: "Cezayir", value: "DZ" },
  { name: "Cibuti", value: "DJ" },
  { name: "Çad", value: "TD" },
  { name: "Çekya", value: "CZ" },
  { name: "Çin", value: "CN" },
  { name: "Danimarka", value: "DK" },
  { name: "Doğu Timor", value: "TL" },
  { name: "Dominik Cumhuriyeti", value: "DO" },
  { name: "Dominika", value: "DM" },
  { name: "Ekvador", value: "EC" },
  { name: "Ekvator Ginesi", value: "GQ" },
  { name: "El Salvador", value: "SV" },
  { name: "Endonezya", value: "ID" },
  { name: "Eritre", value: "ER" },
  { name: "Ermenistan", value: "AM" },
  { name: "Estonya", value: "EE" },
  { name: "Esvatini", value: "SZ" },
  { name: "Etopya", value: "ET" },
  { name: "Fas", value: "MA" },
  { name: "Fiji", value: "FJ" },
  { name: "Fildişi Sahili", value: "CI" },
  { name: "Filipinler", value: "PH" },
  { name: "Finlandiya", value: "FI" },
  { name: "Fransa", value: "FR" },
  { name: "Gabon", value: "GA" },
  { name: "Gambia", value: "GM" },
  { name: "Gana", value: "GH" },
  { name: "Gine", value: "GN" },
  { name: "Gine-Bissau", value: "GW" },
  { name: "Grenada", value: "GD" },
  { name: "Guatemala", value: "GT" },
  { name: "Guyana", value: "GY" },
  { name: "Güney Afrika", value: "ZA" },
  { name: "Güney Kore", value: "KR" },
  { name: "Güney Sudan", value: "SS" },
  { name: "Gürcistan", value: "GE" },
  { name: "Haiti", value: "HT" },
  { name: "Hırvatistan", value: "HR" },
  { name: "Hindistan", value: "IN" },
  { name: "Hollanda", value: "NL" },
  { name: "Honduras", value: "HN" },
  { name: "Irak", value: "IQ" },
  { name: "İran", value: "IR" },
  { name: "İrlanda", value: "IE" },
  { name: "İspanya", value: "ES" },
  { name: "İsrail", value: "IL" },
  { name: "İsveç", value: "SE" },
  { name: "İsviçre", value: "CH" },
  { name: "İtalya", value: "IT" },
  { name: "İzlanda", value: "IS" },
  { name: "Jamaika", value: "JM" },
  { name: "Japonya", value: "JP" },
  { name: "Kamboçya", value: "KH" },
  { name: "Kamerun", value: "CM" },
  { name: "Kanada", value: "CA" },
  { name: "Karadağ", value: "ME" },
  { name: "Katar", value: "QA" },
  { name: "Kazakistan", value: "KZ" },
  { name: "Kenya", value: "KE" },
  { name: "Kırgızistan", value: "KG" },
  { name: "Kiribati", value: "KI" },
  { name: "Kolombiya", value: "CO" },
  { name: "Komorlar", value: "KM" },
  { name: "Kongo", value: "CG" },
  { name: "Kongo Demokratik Cumhuriyeti", value: "CD" },
  { name: "Kosova", value: "XK" },
  { name: "Kosta Rika", value: "CR" },
  { name: "Kuveyt", value: "KW" },
  { name: "Kuzey Kore", value: "KP" },
  { name: "Küba", value: "CU" },
  { name: "Laos", value: "LA" },
  { name: "Lesotho", value: "LS" },
  { name: "Letonya", value: "LV" },
  { name: "Liberya", value: "LR" },
  { name: "Libya", value: "LY" },
  { name: "Liechtenstein", value: "LI" },
  { name: "Litvanya", value: "LT" },
  { name: "Lübnan", value: "LB" },
  { name: "Lüksemburg", value: "LU" },
  { name: "Macaristan", value: "HU" },
  { name: "Madagaskar", value: "MG" },
  { name: "Makedonya", value: "MK" },
  { name: "Malavi", value: "MW" },
  { name: "Maldivler", value: "MV" },
  { name: "Malezya", value: "MY" },
  { name: "Mali", value: "ML" },
  { name: "Malta", value: "MT" },
  { name: "Marshall Adaları", value: "MH" },
  { name: "Meksika", value: "MX" },
  { name: "Mısır", value: "EG" },
  { name: "Mikronezya", value: "FM" },
  { name: "Moğolistan", value: "MN" },
  { name: "Moldova", value: "MD" },
  { name: "Monako", value: "MC" },
  { name: "Moritanya", value: "MR" },
  { name: "Moritius", value: "MU" },
  { name: "Mozambik", value: "MZ" },
  { name: "Myanmar", value: "MM" },
  { name: "Namibya", value: "NA" },
  { name: "Nauru", value: "NR" },
  { name: "Nepal", value: "NP" },
  { name: "Nijer", value: "NE" },
  { name: "Nijerya", value: "NG" },
  { name: "Nikaragua", value: "NI" },
  { name: "Norveç", value: "NO" },
  { name: "Orta Afrika Cumhuriyeti", value: "CF" },
  { name: "Özbekistan", value: "UZ" },
  { name: "Pakistan", value: "PK" },
  { name: "Palau", value: "PW" },
  { name: "Panama", value: "PA" },
  { name: "Papua Yeni Gine", value: "PG" },
  { name: "Paraguay", value: "PY" },
  { name: "Peru", value: "PE" },
  { name: "Polonya", value: "PL" },
  { name: "Portekiz", value: "PT" },
  { name: "Romanya", value: "RO" },
  { name: "Ruanda", value: "RW" },
  { name: "Rusya", value: "RU" },
  { name: "Saint Kitts ve Nevis", value: "KN" },
  { name: "Saint Lucia", value: "LC" },
  { name: "Saint Vincent ve Grenadinler", value: "VC" },
  { name: "Samoa", value: "WS" },
  { name: "San Marino", value: "SM" },
  { name: "Sao Tome ve Principe", value: "ST" },
  { name: "Senegal", value: "SN" },
  { name: "Seyşeller", value: "SC" },
  { name: "Sırbistan", value: "RS" },
  { name: "Sierra Leone", value: "SL" },
  { name: "Singapur", value: "SG" },
  { name: "Slovakya", value: "SK" },
  { name: "Slovenya", value: "SI" },
  { name: "Solomon Adaları", value: "SB" },
  { name: "Somali", value: "SO" },
  { name: "Sri Lanka", value: "LK" },
  { name: "Sudan", value: "SD" },
  { name: "Surinam", value: "SR" },
  { name: "Suriye", value: "SY" },
  { name: "Suudi Arabistan", value: "SA" },
  { name: "Svaziland", value: "SZ" },
  { name: "Şili", value: "CL" },
  { name: "Tacikistan", value: "TJ" },
  { name: "Tanzanya", value: "TZ" },
  { name: "Tayland", value: "TH" },
  { name: "Togo", value: "TG" },
  { name: "Tonga", value: "TO" },
  { name: "Trinidad ve Tobago", value: "TT" },
  { name: "Tunus", value: "TN" },
  { name: "Tuvalu", value: "TV" },
  { name: "Türkiye", value: "TR" },
  { name: "Türkmenistan", value: "TM" },
  { name: "Uganda", value: "UG" },
  { name: "Ukrayna", value: "UA" },
  { name: "Umman", value: "OM" },
  { name: "Uruguay", value: "UY" },
  { name: "Ürdün", value: "JO" },
  { name: "Vanuatu", value: "VU" },
  { name: "Vatikan", value: "VA" },
  { name: "Venezuela", value: "VE" },
  { name: "Vietnam", value: "VN" },
  { name: "Yemen", value: "YE" },
  { name: "Yeni Zelanda", value: "NZ" },
  { name: "Yunanistan", value: "GR" },
  { name: "Zambiya", value: "ZM" },
  { name: "Zimbabve", value: "ZW" },
];

export default countries;
